### ISSUE TITLE
Paket openjdk-8-jre

### ISSUE THREAD

**Issue by simon-hartmann** [dominicpratt/bloonix-install#2]
Mit Debian Jessie lässt sich das Skript nicht bei mir ausführen. Es bricht ab, da dass Paket openjdk-8-jre nicht installierbar ist.  

Mit Debian Stretch hat es anschließend jedoch problemlos geklappt. Danke für das tolle Skript :)

**Comment by dominicpratt** [comment]
Jessie lief bei mir problemlos, gut möglich, dass sich hier was an den Repositories geändert hat.

Da ich aber keine Jessie-Büchse mehr hier stehen habe, kann ich das leider nicht testen... sorry. :-(

**Comment by sixteeN11** [comment]
Gerne kann ich dir eine dafür zur Verfügung stellen, denn ich hänge genau an dem gleichen Thema gerade fest.

**Comment by sixteeN11** [comment]
Java 11 nicht mit Elasticsearch kompatibel
Man muss die Installation zwingen Java 8 zu verwenden.
